ya

diff --git a/.local/bin/ekraneto b/.local/bin/ekraneto
--- a/.local/bin/ekraneto
+++ b/.local/bin/ekraneto
@@ -1,8 +1,10 @@
 #!/usr/bin/sh
 
-p(){ tee "$HOME"/Pictures/screenie_"$(date +'%Y-%m-%d_%H:%M:%S')".png | xclip -selection clipboard -target image/png; }
+bildujo="$(xdg-user-dir PICTURES)";
 
-if [ "$1" = "full" ]; then
+p(){ tee "$bildujo"/ekraneto_"$(date +'%Y-%m-%d_%H:%M:%S')".png | xclip -selection clipboard -target image/png; }
+
+if [ "$1" = "plena" ]; then
   # stolen https://gist.github.com/naelstrof/f9b74b5221cdc324c0911c89a47b8d97
   MONITORS=$(xrandr | grep -o '[0-9]*x[0-9]*[+-][0-9]*[+-][0-9]*');
   XMOUSE=$(xdotool getmouselocation | awk -F "[: ]" '{print $2}');
@@ -23,36 +25,37 @@ if [ "$1" = "full" ]; then
       fi
     fi
   done
-  printf 'Oh no the mouse is in the void!\n' 1>&2;
+  printf 'Ho ne. La muso estas en la malpleno!\n' 1>&2;
   exit 1;
 fi;
 
-if [ "$1" = "select" ]; then
+if [ "$1" = "elektu" ]; then
   maim -quskf png | p;
   exit 0;
 fi;
 
-if [ "$1" = "window" ]; then
+if [ "$1" = "fenestro" ]; then
   maim -quf png -i $(xdotool getactivewindow) | p;
   exit 0;
 fi;
 
-if [ "$1" = "check" ]; then
+if [ "$1" = "kontrolu" ]; then
   err=0;
-  pkgchk(){
+  pakakontrolo(){
     command -v "$1" >/dev/null && return 0;
-    printf 'Error: Program `%s` is not installed\n' "$1" 1>&2;
+    printf 'Erraro: Programo `%s` ne estas instalito\n' "$1" 1>&2;
     err=2;
     return 1;
   }
-  [ -d "$HOME"/Pictures ] || { printf 'Error: %s/Pictures/ does not exist\n' "$HOME"; err=2; };
-  pkgchk maim;
-  pkgchk xclip;
+  [ -d "$bildujo" ] || { printf 'Error: %s ne ekzistas\n' "$bildujo"; err=2; };
+  pakakontrolo awk;
+  pakakontrolo maim;
+  pakakontrolo xclip;
   pkgchk xdotool;
-  [ $err = 0 ] && printf 'Everything is set up!\n';
+  [ $err = 0 ] && printf 'Ĉio estas starita!\n';
   exit $err;
 fi;
 
-printf 'usage: screenie full|select|window|check\n';
+printf 'uzado: ekraneto plena|elektu|fenestro|kontrolu\n';
 exit 1;
 
